# Generated by Django 4.2 on 2023-07-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_remove_themequiz_quiz_quiz_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=2000)),
                ('photo', models.ImageField(upload_to='teachers')),
                ('level', models.CharField(max_length=100)),
            ],
        ),
    ]
