# Generated by Django 4.2 on 2023-07-17 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EduLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': "Ma'lumotlar",
                'verbose_name_plural': "Ma'lumoti",
            },
        ),
        migrations.CreateModel(
            name='ForeignLangs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Chet tili',
                'verbose_name_plural': 'Chet tillari',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Guruh(yoki Patok)')),
            ],
            options={
                'verbose_name': 'Guruh(yoki Patok)',
                'verbose_name_plural': 'Guruh(yoki Patok)lar',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Xona')),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
            },
        ),
        migrations.CreateModel(
            name='ScientificDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ilmiy daraja',
                'verbose_name_plural': 'Ilmiy darajalar',
            },
        ),
        migrations.CreateModel(
            name='ScientificTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ilmiy unvon',
                'verbose_name_plural': 'Ilmiy unvonlar',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Mutaxassislik',
                'verbose_name_plural': 'Mutaxassisliklar',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='F.I.SH')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sanasi")),
                ('birth_place', models.CharField(max_length=255, verbose_name="Tug'ilgan joyi")),
                ('graduated_institution', models.CharField(max_length=255, verbose_name='Tamomlagan OTM')),
                ('work_starting_date', models.DateField(blank=True, null=True, verbose_name='Qachon ishga kirgan')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_teachers', to='TeacherApp.edulevel', verbose_name="Ma'lumoti")),
                ('foreign_langs', models.ManyToManyField(blank=True, related_name='flang_teachers', to='TeacherApp.foreignlangs', verbose_name='Chet tillarini bilish')),
                ('scientific_degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc_degree_teachers', to='TeacherApp.scientificdegree', verbose_name='Ilmiy darajasi')),
                ('scientific_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc_title_teachers', to='TeacherApp.scientifictitle', verbose_name='Ilmiy unvoni')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_teachers', to='TeacherApp.specialty', verbose_name='Mutaxassisligi')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.IntegerField(choices=[(1, "Ma'ruza"), (2, 'Amaliy'), (3, 'Boshqa')], default=3, verbose_name='Dars turi')),
                ('time', models.TimeField(verbose_name='Boshlash vaqti')),
                ('duration', models.IntegerField(default=80, verbose_name='Davomiyligi(minutda)')),
                ('week_day', models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba'), (7, 'Yakshanba')], verbose_name='Hafta kuni')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_lessons', to='TeacherApp.group', verbose_name='Guruh(yoki Patok)')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_lessons', to='TeacherApp.room', verbose_name='Xona')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_lessons', to='TeacherApp.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_lessons', related_query_name="O'qituvchi", to='TeacherApp.teacher')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
            },
        ),
    ]
