# Generated by Django 4.2 on 2023-07-18 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edulevel',
            options={'verbose_name': "Ma'lumoti", 'verbose_name_plural': "Ma'lumot darajalar"},
        ),
        migrations.AddField(
            model_name='teacher',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to='teachers/', verbose_name='Rasm'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='edulevel',
            name='title',
            field=models.CharField(max_length=100, verbose_name="Ma'lumoti"),
        ),
        migrations.AlterField(
            model_name='foreignlangs',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Chet tili'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=80, verbose_name='Davomiyligi'),
        ),
        migrations.AlterField(
            model_name='scientificdegree',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Ilmiy daraja'),
        ),
        migrations.AlterField(
            model_name='scientifictitle',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Ilmiy unvon'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Mutaxassislik'),
        ),
    ]
