# Generated by Django 4.2 on 2023-07-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0002_alter_edulevel_options_teacher_created_teacher_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='education_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_teachers', to='TeacherApp.edulevel', verbose_name="Ma'lumoti"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='scientific_degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sc_degree_teachers', to='TeacherApp.scientificdegree', verbose_name='Ilmiy darajasi'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='scientific_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sc_title_teachers', to='TeacherApp.scientifictitle', verbose_name='Ilmiy unvoni'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_teachers', to='TeacherApp.specialty', verbose_name='Mutaxassisligi'),
        ),
    ]
