# Generated by Django 4.2 on 2023-06-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='blog',
        ),
        migrations.DeleteModel(
            name='BlogTopic',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
